#!/usr/bin/env bash

# PoW
echo "PoW_on_army_enter_province_debug: $(grep -a "PoW_on_army_enter_province_debug" debug.log | wc -l)"
echo "on_commander_travel_to_army: $(grep -a "on_commander_travel_to_army" debug.log | wc -l)"
echo "on_travel_plan_movement_debug: $(grep -a "on_travel_plan_movement_debug" debug.log | wc -l)"
echo "on_travel_plan_movement_prisoner_transit: $(grep -a "on_travel_plan_movement_prisoner_transit" debug.log | wc -l)"
echo "on_travel_plan_complete_prisoner_transit: $(grep -a "on_travel_plan_complete_prisoner_transit" debug.log | wc -l)"
echo "dbg_log prisoner_of_war_capture_effect: $(grep -a "dbg_log prisoner_of_war_capture_effect" debug.log | wc -l)"
echo "PoW_on_imprison: $(grep -a "PoW_on_imprison" debug.log | wc -l)"
echo "PoW_on_release_from_prison: $(grep -a "PoW_on_release_from_prison" debug.log | wc -l)"
echo "PoW_delivery: $(grep -a "PoW_delivery$" debug.log | wc -l)"
echo "PoW_delivery not prisoner: $(grep -a "PoW_delivery not prisoner" debug.log | wc -l)"
echo "PoW_prisoner_transfer_to_army: $(grep -a "PoW_prisoner_transfer_to_army" debug.log | wc -l)"
echo "PoW_commander_story: $(grep -a "PoW_commander_story$" debug.log | wc -l)"
echo "PoW_commander_story_update: $(grep -a "PoW_commander_story_update" debug.log | wc -l)"
echo "PoW_commander_story on_setup: $(grep -a "PoW_commander_story on_setup" debug.log | wc -l)"
echo "PoW_commander_story on_end: $(grep -a "PoW_commander_story on_end" debug.log | wc -l)"
echo "PoW_commander_story on_owner_death: $(grep -a "PoW_commander_story on_owner_death" debug.log | wc -l)"
echo "PoW_commander_story triggered_effect Wrong Army: $(grep -a "PoW_commander_story triggered_effect Wrong Army [^O|L]" debug.log | wc -l)"
echo "PoW_commander_story triggered_effect Wrong Army Owner: $(grep -a "PoW_commander_story triggered_effect Wrong Army Owner" debug.log | wc -l)"
echo "PoW_commander_story triggered_effect Wrong Army Location: $(grep -a "PoW_commander_story triggered_effect Wrong Army Location" debug.log | wc -l)"
echo "PoW_commander_story triggered_effect Wrong Commander Location: $(grep -a "PoW_commander_story triggered_effect Wrong Commander Location" debug.log | wc -l)"
echo "PoW_commander_story triggered_effect Not leading army Commander: $(grep -a "PoW_commander_story triggered_effect Not leading army Commander" debug.log | wc -l)"
